import Head from "next/head";
import Detail from "@/components/detail";

export default function DetailPage({ res, borders }) {
  return (
    <>
      <Head>
        <title>{res.name.common}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Detail country={res} borders={borders}/>
    </>
  );
}

export async function getStaticPaths() {
  const data = await fetch("https://restcountries.com/v3.1/all").then((res) =>
    res.json()
  );
  const allPaths = data.map((country) => {
    return {
      params: {
        id: country.cca3,
      },
    };
  });

  return {
    paths: allPaths,
    fallback: false,
  };
}

export async function getStaticProps(context) {
  const id = context?.params.id;
  const res = await fetch(`https://restcountries.com/v3.1/alpha/${id}?fields=name,region,capital,cca3,population,flags,subregion,tld,currencies,languages,borders`).then(
    (res) => res.json()
  );

  console.log(res);

  if (res.borders) {
    const borderCountries = await Promise.all(
      res.borders.map(async (border) => {
        return await fetch(`https://restcountries.com/v3.1/alpha/${border}`).then(
          (res) => res.json()
        ).then(dat =>  {
          return {name: dat[0].name.common, code: dat[0].cca3}
        });
      })
    );
  
    return {
      props: {
        res,
        borders: borderCountries
      },
    };
  }

  return {
    props: {
      res
    },
  };

  
}
